python render_pointcloud_sphere.py mug_feat_corr.ply
python render_pointcloud_sphere.py mug1.ply
python render_pointcloud_sphere.py mug2_1.ply
python render_pointcloud_sphere.py mug2_2.ply
python render_pointcloud_sphere.py mug2_3.ply
python render_pointcloud_sphere.py mug2_4.ply
python render_pointcloud_sphere.py mug2.ply
python render_pointcloud_sphere.py mug_feat1.ply
python render_pointcloud_sphere.py mug_feat2.ply
python render_pointcloud_sphere.py mug_nocs1.ply
python render_pointcloud_sphere.py mug_nocs2.ply